# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:T/F8mVRccvv1kPdsSvwDtolZCQ+R9IzLiMdWoXUEuATCWzPiN4NTKev7vWGRWHMSi+aHHFwFVZXt5bEjA96D9xqWTq/fs0bScsxejzupIVSIu2BeCb0vliOxRzba4VY1qb+hDEovd/jSakIf00eHGWPmgNSF1CMFpEGeHALm6mFKpEPCke3zn+YatxmbVyTEFhlkMS7yccBQR6Falfo1s76fnh0WVtzPmQJQKrXmng6ajxdfHQ==,iv:vBxtnW/2aSRYLPf/2nCg1b3AC5+azP5X8iIua+GqIdA=,tag:G1Z2P0ni8L+AlH0CC6WW7w==,type:str]
sops:
  age:
    - recipient: age15xt0x3hl5h3qqnagqeny4mzqxdhemampwa6v2wt3x6vkdvtq7fts4q7wjd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAvUHlJV2o0QWVHTkJkWkpa
        RGh1NGVRMVpaRVlBeFNUWC90VWhlSzBkNnkwCi9GVzFYbDJudzlUUjF4UFUzN3g1
        K2ZSSnpvbkFPamhEQm1JanRINytDMVkKLS0tIEtESnMxOHgvV0ZST3ArbGlEM2Z3
        SmRFOS9ZcktoMTVIVjNhT01OK3VpQVEKLPgTP2BS45EjHehJ1ptnR91pN6IUxwVI
        pNZE1FF2sdmoOAsHI5F3JrfUrKKt5sJ9XYJOkF2MNzyNHe9Gy93yzA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T17:06:54Z"
  mac: ENC[AES256_GCM,data:TGyIL3jhf3J1OJtMJk+JBZ7xAwBEbNFm/6LaPeN/V6B2K+pBDTjIfR8EIiA3vneEJyKMn5FXmrwfWXU81SezLBFCR5E4grymLwy20ofF1ISnXcq7hX8HEFAzR1XObrIi4KaT641nuFOifwK1qwkAPxKHX1hbSq3948u92/2VF3c=,iv:vaZFPP5M6nhFqlrUYxc2/75GVnjXH1PmCmN20j64ttU=,tag:wqjZnqf1efG+SSltU5E/7g==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
