# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:6vWKgvrVYCoPUN7z9EB+xBGkFesl06AQs504B7YMij6Sb8wkZONiKQ==,iv:wYse6REgaNTT+l4tVyUhzoGvzVlGhrebei4b+9+j8hw=,tag:2NdSukHiwebOBxjcIyPt6A==,type:str]
sops:
  age:
    - recipient: age15xt0x3hl5h3qqnagqeny4mzqxdhemampwa6v2wt3x6vkdvtq7fts4q7wjd
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBDeS8xSGZZYXBISjNjRzU1
        ZlowQUk1USt0NGRDWDNBTlZqOWdaOFNIT1F3CjdUUzlrNmpCajJBRkJDVWlkNm1s
        aFdzRjg0ZUxlTzRTK3pMYXV6Q1Nsc3MKLS0tIHVwRHM2elhUMUZsbzg1ekpwbURv
        cVJrN2NnVTA4am5objF0NEc0elYwT0UK7IaGeRuJn0blgjPmJTKT5YRqtJ2WZCNe
        Sa8hVG5wM09R2IasxEbtGVE7WhW0z/uq2KeadhBvbTtvcQe9UF8Hmg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-05-01T17:06:54Z"
  mac: ENC[AES256_GCM,data:Po79oWc359MGZGRLar1pVcNacQ6TypFErXu6xjncBvwndfwJ1Eva05x0x9B3Jt75xX3D4tks5Y2ZufvSv4RXyL4lR5q1pM77Sf2U3+0u92/R0aZE3n7m5ecmqY6Oq12dxwHAxLAyJMQngGGrI8fzES5RpFNEDcCucF0Lnya0YZk=,iv:osta9OMzGFOI7WC599i2xC0/zICp5812oDlI3JSoHQM=,tag:htmTW8Jlukj1BnaXnJTAkw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.10.2
