---
# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
  install:
    timeout: 10m0s
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  dependsOn:
    - name: cloudflared
      namespace: network
  # See https://github.com/bjw-s/helm-charts/blob/main/charts/library/common/values.yaml
  values:
    controllers:
          main:
            containers:
              app:
                image:
                  repository: docker.io/fallenbagel/jellyseerr
                  tag: 2.5.2
                env:
                  LOG_LEVEL: "info"
                probes:
                  liveness: &probes
                    enabled: true
                    custom: true
                    spec:
                      httpGet:
                        path: /api/v1/status
                        port: 5055
                      initialDelaySeconds: 0
                      periodSeconds: 10
                      timeoutSeconds: 1
                      failureThreshold: 3
                  readiness: 3

    persistence:
      config:
        enabled: true
        type: emptyDir
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      tmp:
        type: emptyDir

    service:
      main:
        controller: main
        #type: LoadBalancer
       # loadBalancerIP: ${CLUSTER_EXTERNAL_SUBNET_PREFIX}.${CLUSTER_LB_JELLYFIN}
       # externalIPs:
        #- ${CLUSTER_EXTERNAL_SUBNET_PREFIX}.${CLUSTER_LB_JELLYFIN}
        #externalTrafficPolicy: Local
        ports:
          http:
            port: 5055
    ingress:
      main:
        className: external
        annotations:
          external-dns.alpha.kubernetes.io/target: "external.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: main
                  port: http
    # ingress:
    #   main:
    #     enabled: true
    #     annotations:
    #       hajimari.io/enable: "true"
    #       hajimari.io/icon: simple-icons:jellyfin
    #       hajimari.io/info: Video and Music Player
    #       hajimari.io/group: media
    #       nginx.ingress.kubernetes.io/enable-global-auth: "false"
    #     hosts:
    #     - host: jellyfin.home.${CLUSTER_DOMAIN}
    #       paths: &paths
    #       - path: /
    #         pathType: Prefix
    #         service:
    #           identifier: main
    #           port: http
    #     - host: jellyfin.pub.${CLUSTER_DOMAIN}
    #       paths: *paths